version: '3'
services:
  webserver:
    container_name: laravel-front
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8029:80
    volumes:
      - ./laravel/:/vhost
#      - app_cache_volume:/sesame/var/cache
#      - app_vendor_volume:/sesame/vendor
    working_dir: /vhost
    environment:
      APP_SECRET: 7c570677b6270289dc9a2c927e2eb292
      DATABASE_URL: mysql://user:admin123@db:3306/database
      VIRTUAL_HOST: localhost
      APP_KEY: base64:Mhb/scHxwFpUmozyOhdoVtueWsGAzp8Tw7bNbu3XmL8=
  db:
    image: mysql:5.7
    ports:
      - "3349:3306"
    volumes:
      - ./var/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: admin123
    container_name: laravel-db
